"""Create pallets table

Revision ID: 00005
Revises: 00004
Create Date: 2026-06-06 01:36:21.055268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00005'
down_revision: Union[str, None] = '00004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pallets',
    sa.Column('supplier_uuid', sa.UUID(), nullable=False),
    sa.Column('area_uuid', sa.UUID(), nullable=False),
    sa.Column('unit_uuid', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_uuid'], ['areas.uuid'], ),
    sa.ForeignKeyConstraint(['supplier_uuid'], ['suppliers.uuid'], ),
    sa.ForeignKeyConstraint(['unit_uuid'], ['units.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('supplier_uuid', 'area_uuid', 'unit_uuid', name='uq_supplier_area_unit')
    )
    op.create_index(op.f('ix_pallets_created_at'), 'pallets', ['created_at'], unique=False)
    op.create_index(op.f('ix_pallets_uuid'), 'pallets', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pallets_uuid'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_created_at'), table_name='pallets')
    op.drop_table('pallets')
    # ### end Alembic commands ###
